// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: atomos.proto

package go_atomos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LogLevel int32

const (
	LogLevel_Debug LogLevel = 0
	LogLevel_Info  LogLevel = 1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Error LogLevel = 3
	LogLevel_Fatal LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
		4: "Fatal",
	}
	LogLevel_value = map[string]int32{
		"Debug": 0,
		"Info":  1,
		"Warn":  2,
		"Error": 3,
		"Fatal": 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_atomos_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_atomos_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{0}
}

type AtomId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node    string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Element string `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AtomId) Reset() {
	*x = AtomId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomId) ProtoMessage() {}

func (x *AtomId) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomId.ProtoReflect.Descriptor instead.
func (*AtomId) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{0}
}

func (x *AtomId) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *AtomId) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

func (x *AtomId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *AtomId                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Level   LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=go_atomos.LogLevel" json:"level,omitempty"`
	Message string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogMail) Reset() {
	*x = LogMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMail) ProtoMessage() {}

func (x *LogMail) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMail.ProtoReflect.Descriptor instead.
func (*LogMail) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{1}
}

func (x *LogMail) GetId() *AtomId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LogMail) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogMail) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Debug
}

func (x *LogMail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Nil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nil) Reset() {
	*x = Nil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{2}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node        string             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	LogPath     string             `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	CosmosLocal *CosmosLocalConfig `protobuf:"bytes,3,opt,name=cosmos_local,json=cosmosLocal,proto3" json:"cosmos_local,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Config) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *Config) GetCosmosLocal() *CosmosLocalConfig {
	if x != nil {
		return x.CosmosLocal
	}
	return nil
}

type CosmosLocalConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements map[string]*ElementConfig `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CosmosLocalConfig) Reset() {
	*x = CosmosLocalConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosLocalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosLocalConfig) ProtoMessage() {}

func (x *CosmosLocalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosLocalConfig.ProtoReflect.Descriptor instead.
func (*CosmosLocalConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{4}
}

func (x *CosmosLocalConfig) GetElements() map[string]*ElementConfig {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ElementConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     uint64                       `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LogLevel    LogLevel                     `protobuf:"varint,3,opt,name=log_level,json=logLevel,proto3,enum=go_atomos.LogLevel" json:"log_level,omitempty"`
	AtomInitNum int32                        `protobuf:"varint,4,opt,name=atom_init_num,json=atomInitNum,proto3" json:"atom_init_num,omitempty"`
	Calls       map[string]*AtomosCallConfig `protobuf:"bytes,5,rep,name=calls,proto3" json:"calls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ElementConfig) Reset() {
	*x = ElementConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementConfig) ProtoMessage() {}

func (x *ElementConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementConfig.ProtoReflect.Descriptor instead.
func (*ElementConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{5}
}

func (x *ElementConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ElementConfig) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ElementConfig) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_Debug
}

func (x *ElementConfig) GetAtomInitNum() int32 {
	if x != nil {
		return x.AtomInitNum
	}
	return 0
}

func (x *ElementConfig) GetCalls() map[string]*AtomosCallConfig {
	if x != nil {
		return x.Calls
	}
	return nil
}

type AtomosCallConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AtomosCallConfig) Reset() {
	*x = AtomosCallConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomosCallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomosCallConfig) ProtoMessage() {}

func (x *AtomosCallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomosCallConfig.ProtoReflect.Descriptor instead.
func (*AtomosCallConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{6}
}

var File_atomos_proto protoreflect.FileDescriptor

var file_atomos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x06, 0x41, 0x74,
	0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x4d, 0x61,
	0x69, 0x6c, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x6f, 0x6d, 0x49,
	0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73,
	0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x05, 0x0a, 0x03, 0x4e, 0x69,
	0x6c, 0x22, 0x78, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x3f, 0x0a, 0x0c, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0b,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x22, 0xb2, 0x01, 0x0a, 0x11,
	0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x46, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e,
	0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x55, 0x0a, 0x0d, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f,
	0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xa5, 0x02, 0x0a, 0x0d, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x30, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e,
	0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x74, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x74, 0x6f, 0x6d, 0x49,
	0x6e, 0x69, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x39, 0x0a, 0x05, 0x63, 0x61, 0x6c, 0x6c, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f,
	0x73, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x61, 0x6c, 0x6c,
	0x73, 0x1a, 0x55, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x74, 0x6f,
	0x6d, 0x6f, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x74, 0x6f, 0x6d,
	0x6f, 0x73, 0x43, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2a, 0x3f, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x57, 0x61, 0x72, 0x6e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x74, 0x61, 0x6c, 0x10, 0x04, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_atomos_proto_rawDescOnce sync.Once
	file_atomos_proto_rawDescData = file_atomos_proto_rawDesc
)

func file_atomos_proto_rawDescGZIP() []byte {
	file_atomos_proto_rawDescOnce.Do(func() {
		file_atomos_proto_rawDescData = protoimpl.X.CompressGZIP(file_atomos_proto_rawDescData)
	})
	return file_atomos_proto_rawDescData
}

var file_atomos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atomos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_atomos_proto_goTypes = []interface{}{
	(LogLevel)(0),                 // 0: go_atomos.LogLevel
	(*AtomId)(nil),                // 1: go_atomos.AtomId
	(*LogMail)(nil),               // 2: go_atomos.LogMail
	(*Nil)(nil),                   // 3: go_atomos.Nil
	(*Config)(nil),                // 4: go_atomos.Config
	(*CosmosLocalConfig)(nil),     // 5: go_atomos.CosmosLocalConfig
	(*ElementConfig)(nil),         // 6: go_atomos.ElementConfig
	(*AtomosCallConfig)(nil),      // 7: go_atomos.AtomosCallConfig
	nil,                           // 8: go_atomos.CosmosLocalConfig.ElementsEntry
	nil,                           // 9: go_atomos.ElementConfig.CallsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_atomos_proto_depIdxs = []int32{
	1,  // 0: go_atomos.LogMail.id:type_name -> go_atomos.AtomId
	10, // 1: go_atomos.LogMail.time:type_name -> google.protobuf.Timestamp
	0,  // 2: go_atomos.LogMail.level:type_name -> go_atomos.LogLevel
	5,  // 3: go_atomos.Config.cosmos_local:type_name -> go_atomos.CosmosLocalConfig
	8,  // 4: go_atomos.CosmosLocalConfig.elements:type_name -> go_atomos.CosmosLocalConfig.ElementsEntry
	0,  // 5: go_atomos.ElementConfig.log_level:type_name -> go_atomos.LogLevel
	9,  // 6: go_atomos.ElementConfig.calls:type_name -> go_atomos.ElementConfig.CallsEntry
	6,  // 7: go_atomos.CosmosLocalConfig.ElementsEntry.value:type_name -> go_atomos.ElementConfig
	7,  // 8: go_atomos.ElementConfig.CallsEntry.value:type_name -> go_atomos.AtomosCallConfig
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_atomos_proto_init() }
func file_atomos_proto_init() {
	if File_atomos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_atomos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtomId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosLocalConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtomosCallConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_atomos_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atomos_proto_goTypes,
		DependencyIndexes: file_atomos_proto_depIdxs,
		EnumInfos:         file_atomos_proto_enumTypes,
		MessageInfos:      file_atomos_proto_msgTypes,
	}.Build()
	File_atomos_proto = out.File
	file_atomos_proto_rawDesc = nil
	file_atomos_proto_goTypes = nil
	file_atomos_proto_depIdxs = nil
}
