// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: atomos.proto

package go_atomos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDType int32

const (
	IDType_InvalidIDType IDType = 0
	IDType_Process       IDType = 1
	IDType_Main          IDType = 2
	IDType_Cosmos        IDType = 3
	IDType_Element       IDType = 4
	IDType_Atomos        IDType = 5
)

// Enum value maps for IDType.
var (
	IDType_name = map[int32]string{
		0: "InvalidIDType",
		1: "Process",
		2: "Main",
		3: "Cosmos",
		4: "Element",
		5: "Atomos",
	}
	IDType_value = map[string]int32{
		"InvalidIDType": 0,
		"Process":       1,
		"Main":          2,
		"Cosmos":        3,
		"Element":       4,
		"Atomos":        5,
	}
)

func (x IDType) Enum() *IDType {
	p := new(IDType)
	*p = x
	return p
}

func (x IDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IDType) Descriptor() protoreflect.EnumDescriptor {
	return file_atomos_proto_enumTypes[0].Descriptor()
}

func (IDType) Type() protoreflect.EnumType {
	return &file_atomos_proto_enumTypes[0]
}

func (x IDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IDType.Descriptor instead.
func (IDType) EnumDescriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{0}
}

type LogLevel int32

const (
	LogLevel_Debug LogLevel = 0
	LogLevel_Info  LogLevel = 1
	LogLevel_Warn  LogLevel = 2
	LogLevel_Error LogLevel = 3
	LogLevel_Fatal LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
		4: "Fatal",
	}
	LogLevel_value = map[string]int32{
		"Debug": 0,
		"Info":  1,
		"Warn":  2,
		"Error": 3,
		"Fatal": 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_atomos_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_atomos_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{1}
}

type CosmosWatchMessageType int32

const (
	CosmosWatchMessageType_Init CosmosWatchMessageType = 0
)

// Enum value maps for CosmosWatchMessageType.
var (
	CosmosWatchMessageType_name = map[int32]string{
		0: "Init",
	}
	CosmosWatchMessageType_value = map[string]int32{
		"Init": 0,
	}
)

func (x CosmosWatchMessageType) Enum() *CosmosWatchMessageType {
	p := new(CosmosWatchMessageType)
	*p = x
	return p
}

func (x CosmosWatchMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CosmosWatchMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_atomos_proto_enumTypes[2].Descriptor()
}

func (CosmosWatchMessageType) Type() protoreflect.EnumType {
	return &file_atomos_proto_enumTypes[2]
}

func (x CosmosWatchMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CosmosWatchMessageType.Descriptor instead.
func (CosmosWatchMessageType) EnumDescriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{2}
}

type IDInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    IDType     `protobuf:"varint,1,opt,name=type,proto3,enum=atomos.IDType" json:"type,omitempty"`
	Cosmos  string     `protobuf:"bytes,2,opt,name=cosmos,proto3" json:"cosmos,omitempty"`
	Element string     `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Atomos  string     `protobuf:"bytes,4,opt,name=atomos,proto3" json:"atomos,omitempty"`
	Ext     *anypb.Any `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
}

func (x *IDInfo) Reset() {
	*x = IDInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDInfo) ProtoMessage() {}

func (x *IDInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDInfo.ProtoReflect.Descriptor instead.
func (*IDInfo) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{0}
}

func (x *IDInfo) GetType() IDType {
	if x != nil {
		return x.Type
	}
	return IDType_InvalidIDType
}

func (x *IDInfo) GetCosmos() string {
	if x != nil {
		return x.Cosmos
	}
	return ""
}

func (x *IDInfo) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

func (x *IDInfo) GetAtomos() string {
	if x != nil {
		return x.Atomos
	}
	return ""
}

func (x *IDInfo) GetExt() *anypb.Any {
	if x != nil {
		return x.Ext
	}
	return nil
}

type LogMail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *IDInfo                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Level   LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=atomos.LogLevel" json:"level,omitempty"`
	Message string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *LogMail) Reset() {
	*x = LogMail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMail) ProtoMessage() {}

func (x *LogMail) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMail.ProtoReflect.Descriptor instead.
func (*LogMail) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{1}
}

func (x *LogMail) GetId() *IDInfo {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LogMail) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *LogMail) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_Debug
}

func (x *LogMail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Panic   string             `protobuf:"bytes,3,opt,name=panic,proto3" json:"panic,omitempty"`
	Stacks  []*ErrorCallerInfo `protobuf:"bytes,4,rep,name=stacks,proto3" json:"stacks,omitempty"`
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorInfo) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetPanic() string {
	if x != nil {
		return x.Panic
	}
	return ""
}

func (x *ErrorInfo) GetStacks() []*ErrorCallerInfo {
	if x != nil {
		return x.Stacks
	}
	return nil
}

type ErrorCallerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *IDInfo `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason   string  `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	File     string  `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Line     uint32  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Args     []byte  `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	ArgsRead string  `protobuf:"bytes,6,opt,name=args_read,json=argsRead,proto3" json:"args_read,omitempty"`
}

func (x *ErrorCallerInfo) Reset() {
	*x = ErrorCallerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorCallerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorCallerInfo) ProtoMessage() {}

func (x *ErrorCallerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorCallerInfo.ProtoReflect.Descriptor instead.
func (*ErrorCallerInfo) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorCallerInfo) GetId() *IDInfo {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ErrorCallerInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorCallerInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ErrorCallerInfo) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *ErrorCallerInfo) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ErrorCallerInfo) GetArgsRead() string {
	if x != nil {
		return x.ArgsRead
	}
	return ""
}

type Nil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Nil) Reset() {
	*x = Nil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{4}
}

type Int32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *Int32) Reset() {
	*x = Int32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32) ProtoMessage() {}

func (x *Int32) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32.ProtoReflect.Descriptor instead.
func (*Int32) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{5}
}

func (x *Int32) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type Int64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int64 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *Int64) Reset() {
	*x = Int64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64) ProtoMessage() {}

func (x *Int64) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64.ProtoReflect.Descriptor instead.
func (*Int64) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{6}
}

func (x *Int64) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

type UInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N uint32 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *UInt32) Reset() {
	*x = UInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt32) ProtoMessage() {}

func (x *UInt32) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt32.ProtoReflect.Descriptor instead.
func (*UInt32) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{7}
}

func (x *UInt32) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type UInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I uint64 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
}

func (x *UInt64) Reset() {
	*x = UInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt64) ProtoMessage() {}

func (x *UInt64) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt64.ProtoReflect.Descriptor instead.
func (*UInt64) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{8}
}

func (x *UInt64) GetI() uint64 {
	if x != nil {
		return x.I
	}
	return 0
}

type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{9}
}

func (x *String) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node         string              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	LogPath      string              `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	LogLevel     LogLevel            `protobuf:"varint,3,opt,name=log_level,json=logLevel,proto3,enum=atomos.LogLevel" json:"log_level,omitempty"`
	EnableCert   *CertConfig         `protobuf:"bytes,4,opt,name=enable_cert,json=enableCert,proto3" json:"enable_cert,omitempty"`
	EnableServer *RemoteServerConfig `protobuf:"bytes,5,opt,name=enable_server,json=enableServer,proto3" json:"enable_server,omitempty"`
	EnableTelnet *TelnetServerConfig `protobuf:"bytes,6,opt,name=enable_telnet,json=enableTelnet,proto3" json:"enable_telnet,omitempty"`
	Customize    map[string]string   `protobuf:"bytes,7,rep,name=customize,proto3" json:"customize,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{10}
}

func (x *Config) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Config) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *Config) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_Debug
}

func (x *Config) GetEnableCert() *CertConfig {
	if x != nil {
		return x.EnableCert
	}
	return nil
}

func (x *Config) GetEnableServer() *RemoteServerConfig {
	if x != nil {
		return x.EnableServer
	}
	return nil
}

func (x *Config) GetEnableTelnet() *TelnetServerConfig {
	if x != nil {
		return x.EnableTelnet
	}
	return nil
}

func (x *Config) GetCustomize() map[string]string {
	if x != nil {
		return x.Customize
	}
	return nil
}

type RemoteServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *RemoteServerConfig) Reset() {
	*x = RemoteServerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteServerConfig) ProtoMessage() {}

func (x *RemoteServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteServerConfig.ProtoReflect.Descriptor instead.
func (*RemoteServerConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{11}
}

func (x *RemoteServerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RemoteServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TelnetServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Network string             `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Address string             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Admin   *TelnetAdminConfig `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *TelnetServerConfig) Reset() {
	*x = TelnetServerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelnetServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelnetServerConfig) ProtoMessage() {}

func (x *TelnetServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelnetServerConfig.ProtoReflect.Descriptor instead.
func (*TelnetServerConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{12}
}

func (x *TelnetServerConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *TelnetServerConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TelnetServerConfig) GetAdmin() *TelnetAdminConfig {
	if x != nil {
		return x.Admin
	}
	return nil
}

type TelnetAdminConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *TelnetAdminConfig) Reset() {
	*x = TelnetAdminConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelnetAdminConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelnetAdminConfig) ProtoMessage() {}

func (x *TelnetAdminConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelnetAdminConfig.ProtoReflect.Descriptor instead.
func (*TelnetAdminConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{13}
}

func (x *TelnetAdminConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TelnetAdminConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CertConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertPath           string `protobuf:"bytes,1,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath            string `protobuf:"bytes,2,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	InsecureSkipVerify bool   `protobuf:"varint,3,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
}

func (x *CertConfig) Reset() {
	*x = CertConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertConfig) ProtoMessage() {}

func (x *CertConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertConfig.ProtoReflect.Descriptor instead.
func (*CertConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{14}
}

func (x *CertConfig) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *CertConfig) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *CertConfig) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type CosmosLocalConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName     string              `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	EnableRemote *RemoteServerConfig `protobuf:"bytes,2,opt,name=enable_remote,json=enableRemote,proto3" json:"enable_remote,omitempty"`
	Elements     []string            `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *CosmosLocalConfig) Reset() {
	*x = CosmosLocalConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosLocalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosLocalConfig) ProtoMessage() {}

func (x *CosmosLocalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosLocalConfig.ProtoReflect.Descriptor instead.
func (*CosmosLocalConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{15}
}

func (x *CosmosLocalConfig) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CosmosLocalConfig) GetEnableRemote() *RemoteServerConfig {
	if x != nil {
		return x.EnableRemote
	}
	return nil
}

func (x *CosmosLocalConfig) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ElementConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     uint64                        `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LogLevel    LogLevel                      `protobuf:"varint,3,opt,name=log_level,json=logLevel,proto3,enum=atomos.LogLevel" json:"log_level,omitempty"`
	AtomInitNum int32                         `protobuf:"varint,4,opt,name=atom_init_num,json=atomInitNum,proto3" json:"atom_init_num,omitempty"`
	Messages    map[string]*AtomMessageConfig `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ElementConfig) Reset() {
	*x = ElementConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementConfig) ProtoMessage() {}

func (x *ElementConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementConfig.ProtoReflect.Descriptor instead.
func (*ElementConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{16}
}

func (x *ElementConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ElementConfig) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ElementConfig) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_Debug
}

func (x *ElementConfig) GetAtomInitNum() int32 {
	if x != nil {
		return x.AtomInitNum
	}
	return 0
}

func (x *ElementConfig) GetMessages() map[string]*AtomMessageConfig {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AtomMessageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In  *anypb.Any `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Out *anypb.Any `protobuf:"bytes,2,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *AtomMessageConfig) Reset() {
	*x = AtomMessageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AtomMessageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomMessageConfig) ProtoMessage() {}

func (x *AtomMessageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomMessageConfig.ProtoReflect.Descriptor instead.
func (*AtomMessageConfig) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{17}
}

func (x *AtomMessageConfig) GetIn() *anypb.Any {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *AtomMessageConfig) GetOut() *anypb.Any {
	if x != nil {
		return x.Out
	}
	return nil
}

type CosmosWatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType CosmosWatchMessageType   `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=atomos.CosmosWatchMessageType" json:"message_type,omitempty"`
	InitMessage *CosmosRemoteConnectInit `protobuf:"bytes,2,opt,name=init_message,json=initMessage,proto3" json:"init_message,omitempty"`
}

func (x *CosmosWatch) Reset() {
	*x = CosmosWatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosWatch) ProtoMessage() {}

func (x *CosmosWatch) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosWatch.ProtoReflect.Descriptor instead.
func (*CosmosWatch) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{18}
}

func (x *CosmosWatch) GetMessageType() CosmosWatchMessageType {
	if x != nil {
		return x.MessageType
	}
	return CosmosWatchMessageType_Init
}

func (x *CosmosWatch) GetInitMessage() *CosmosRemoteConnectInit {
	if x != nil {
		return x.InitMessage
	}
	return nil
}

type CosmosRemoteConnectInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *CosmosLocalConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CosmosRemoteConnectInit) Reset() {
	*x = CosmosRemoteConnectInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosRemoteConnectInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosRemoteConnectInit) ProtoMessage() {}

func (x *CosmosRemoteConnectInit) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosRemoteConnectInit.ProtoReflect.Descriptor instead.
func (*CosmosRemoteConnectInit) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{19}
}

func (x *CosmosRemoteConnectInit) GetConfig() *CosmosLocalConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CosmosRemoteGetAtomIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element string `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CosmosRemoteGetAtomIdReq) Reset() {
	*x = CosmosRemoteGetAtomIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosRemoteGetAtomIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosRemoteGetAtomIdReq) ProtoMessage() {}

func (x *CosmosRemoteGetAtomIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosRemoteGetAtomIdReq.ProtoReflect.Descriptor instead.
func (*CosmosRemoteGetAtomIdReq) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{20}
}

func (x *CosmosRemoteGetAtomIdReq) GetElement() string {
	if x != nil {
		return x.Element
	}
	return ""
}

func (x *CosmosRemoteGetAtomIdReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CosmosRemoteGetAtomIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Has   bool   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CosmosRemoteGetAtomIdResp) Reset() {
	*x = CosmosRemoteGetAtomIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosRemoteGetAtomIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosRemoteGetAtomIdResp) ProtoMessage() {}

func (x *CosmosRemoteGetAtomIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosRemoteGetAtomIdResp.ProtoReflect.Descriptor instead.
func (*CosmosRemoteGetAtomIdResp) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{21}
}

func (x *CosmosRemoteGetAtomIdResp) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

func (x *CosmosRemoteGetAtomIdResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CosmosRemoteMessagingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    *IDInfo    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To      *IDInfo    `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Message string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Args    *anypb.Any `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *CosmosRemoteMessagingReq) Reset() {
	*x = CosmosRemoteMessagingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosRemoteMessagingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosRemoteMessagingReq) ProtoMessage() {}

func (x *CosmosRemoteMessagingReq) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosRemoteMessagingReq.ProtoReflect.Descriptor instead.
func (*CosmosRemoteMessagingReq) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{22}
}

func (x *CosmosRemoteMessagingReq) GetFrom() *IDInfo {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CosmosRemoteMessagingReq) GetTo() *IDInfo {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *CosmosRemoteMessagingReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CosmosRemoteMessagingReq) GetArgs() *anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type CosmosRemoteMessagingResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Has   bool       `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	Reply *anypb.Any `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	Error string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CosmosRemoteMessagingResp) Reset() {
	*x = CosmosRemoteMessagingResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_atomos_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosRemoteMessagingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosRemoteMessagingResp) ProtoMessage() {}

func (x *CosmosRemoteMessagingResp) ProtoReflect() protoreflect.Message {
	mi := &file_atomos_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosRemoteMessagingResp.ProtoReflect.Descriptor instead.
func (*CosmosRemoteMessagingResp) Descriptor() ([]byte, []int) {
	return file_atomos_proto_rawDescGZIP(), []int{23}
}

func (x *CosmosRemoteMessagingResp) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

func (x *CosmosRemoteMessagingResp) GetReply() *anypb.Any {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *CosmosRemoteMessagingResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_atomos_proto protoreflect.FileDescriptor

var file_atomos_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x06, 0x49, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x74,
	0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x44, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x12, 0x26, 0x0a, 0x03, 0x65,
	0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03,
	0x65, 0x78, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x4d, 0x61, 0x69, 0x6c, 0x12,
	0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x74,
	0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x61, 0x6e, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61,
	0x6e, 0x69, 0x63, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x44,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x72, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x72, 0x67, 0x73, 0x52, 0x65, 0x61, 0x64, 0x22, 0x05, 0x0a, 0x03, 0x4e, 0x69, 0x6c,
	0x22, 0x15, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x6e, 0x22, 0x15, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x22, 0x16,
	0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x01, 0x6e, 0x22, 0x16, 0x0a, 0x06, 0x55, 0x49, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x69, 0x22, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x98, 0x03, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x2d, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x33, 0x0a, 0x0b, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x43, 0x65,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x43, 0x65, 0x72, 0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x74,
	0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x74, 0x65, 0x6c, 0x6e, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x54, 0x65, 0x6c, 0x6e, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x54, 0x65, 0x6c, 0x6e, 0x65, 0x74, 0x12, 0x3b, 0x0a, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x74, 0x6f, 0x6d,
	0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x69, 0x7a, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x69, 0x7a, 0x65, 0x1a, 0x3c, 0x0a, 0x0e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x3c, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22,
	0x79, 0x0a, 0x12, 0x54, 0x65, 0x6c, 0x6e, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f,
	0x73, 0x2e, 0x54, 0x65, 0x6c, 0x6e, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x4b, 0x0a, 0x11, 0x54, 0x65,
	0x6c, 0x6e, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x76, 0x0a, 0x0a, 0x43, 0x65, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x72, 0x74, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x30, 0x0a,
	0x14, 0x69, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x69, 0x6e, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x53, 0x6b, 0x69, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x22,
	0x8d, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x74, 0x6f, 0x6d,
	0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0c, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0xa9, 0x02, 0x0a, 0x0d, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x22,
	0x0a, 0x0d, 0x61, 0x74, 0x6f, 0x6d, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x74, 0x6f, 0x6d, 0x49, 0x6e, 0x69, 0x74, 0x4e,
	0x75, 0x6d, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x1a, 0x56, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x41,
	0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x61, 0x0a, 0x11, 0x41,
	0x74, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x24, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x22, 0x94,
	0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x57, 0x61, 0x74, 0x63, 0x68, 0x12, 0x41,
	0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x43, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x57, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x42, 0x0a, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73,
	0x2e, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a, 0x17, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x69, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x22, 0x48, 0x0a, 0x18, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x47, 0x65, 0x74, 0x41, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a,
	0x19, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x68, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0xa2, 0x01, 0x0a, 0x18, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e,
	0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x6f, 0x0a, 0x19, 0x43, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x03, 0x68, 0x61, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x57, 0x0a, 0x06, 0x49, 0x44, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x49, 0x44, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x10,
	0x05, 0x2a, 0x3f, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x09, 0x0a,
	0x05, 0x44, 0x65, 0x62, 0x75, 0x67, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x61, 0x72, 0x6e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x61, 0x74, 0x61, 0x6c,
	0x10, 0x04, 0x2a, 0x22, 0x0a, 0x16, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x6e, 0x69, 0x74, 0x10, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x77, 0x61, 0x6e, 0x67, 0x74, 0x6f, 0x75, 0x2f, 0x67, 0x6f,
	0x2d, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_atomos_proto_rawDescOnce sync.Once
	file_atomos_proto_rawDescData = file_atomos_proto_rawDesc
)

func file_atomos_proto_rawDescGZIP() []byte {
	file_atomos_proto_rawDescOnce.Do(func() {
		file_atomos_proto_rawDescData = protoimpl.X.CompressGZIP(file_atomos_proto_rawDescData)
	})
	return file_atomos_proto_rawDescData
}

var file_atomos_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_atomos_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_atomos_proto_goTypes = []interface{}{
	(IDType)(0),                       // 0: atomos.IDType
	(LogLevel)(0),                     // 1: atomos.LogLevel
	(CosmosWatchMessageType)(0),       // 2: atomos.CosmosWatchMessageType
	(*IDInfo)(nil),                    // 3: atomos.IDInfo
	(*LogMail)(nil),                   // 4: atomos.LogMail
	(*ErrorInfo)(nil),                 // 5: atomos.ErrorInfo
	(*ErrorCallerInfo)(nil),           // 6: atomos.ErrorCallerInfo
	(*Nil)(nil),                       // 7: atomos.Nil
	(*Int32)(nil),                     // 8: atomos.Int32
	(*Int64)(nil),                     // 9: atomos.Int64
	(*UInt32)(nil),                    // 10: atomos.UInt32
	(*UInt64)(nil),                    // 11: atomos.UInt64
	(*String)(nil),                    // 12: atomos.String
	(*Config)(nil),                    // 13: atomos.Config
	(*RemoteServerConfig)(nil),        // 14: atomos.RemoteServerConfig
	(*TelnetServerConfig)(nil),        // 15: atomos.TelnetServerConfig
	(*TelnetAdminConfig)(nil),         // 16: atomos.TelnetAdminConfig
	(*CertConfig)(nil),                // 17: atomos.CertConfig
	(*CosmosLocalConfig)(nil),         // 18: atomos.CosmosLocalConfig
	(*ElementConfig)(nil),             // 19: atomos.ElementConfig
	(*AtomMessageConfig)(nil),         // 20: atomos.AtomMessageConfig
	(*CosmosWatch)(nil),               // 21: atomos.CosmosWatch
	(*CosmosRemoteConnectInit)(nil),   // 22: atomos.CosmosRemoteConnectInit
	(*CosmosRemoteGetAtomIdReq)(nil),  // 23: atomos.CosmosRemoteGetAtomIdReq
	(*CosmosRemoteGetAtomIdResp)(nil), // 24: atomos.CosmosRemoteGetAtomIdResp
	(*CosmosRemoteMessagingReq)(nil),  // 25: atomos.CosmosRemoteMessagingReq
	(*CosmosRemoteMessagingResp)(nil), // 26: atomos.CosmosRemoteMessagingResp
	nil,                               // 27: atomos.Config.CustomizeEntry
	nil,                               // 28: atomos.ElementConfig.MessagesEntry
	(*anypb.Any)(nil),                 // 29: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),     // 30: google.protobuf.Timestamp
}
var file_atomos_proto_depIdxs = []int32{
	0,  // 0: atomos.IDInfo.type:type_name -> atomos.IDType
	29, // 1: atomos.IDInfo.ext:type_name -> google.protobuf.Any
	3,  // 2: atomos.LogMail.id:type_name -> atomos.IDInfo
	30, // 3: atomos.LogMail.time:type_name -> google.protobuf.Timestamp
	1,  // 4: atomos.LogMail.level:type_name -> atomos.LogLevel
	6,  // 5: atomos.ErrorInfo.stacks:type_name -> atomos.ErrorCallerInfo
	3,  // 6: atomos.ErrorCallerInfo.id:type_name -> atomos.IDInfo
	1,  // 7: atomos.Config.log_level:type_name -> atomos.LogLevel
	17, // 8: atomos.Config.enable_cert:type_name -> atomos.CertConfig
	14, // 9: atomos.Config.enable_server:type_name -> atomos.RemoteServerConfig
	15, // 10: atomos.Config.enable_telnet:type_name -> atomos.TelnetServerConfig
	27, // 11: atomos.Config.customize:type_name -> atomos.Config.CustomizeEntry
	16, // 12: atomos.TelnetServerConfig.admin:type_name -> atomos.TelnetAdminConfig
	14, // 13: atomos.CosmosLocalConfig.enable_remote:type_name -> atomos.RemoteServerConfig
	1,  // 14: atomos.ElementConfig.log_level:type_name -> atomos.LogLevel
	28, // 15: atomos.ElementConfig.messages:type_name -> atomos.ElementConfig.MessagesEntry
	29, // 16: atomos.AtomMessageConfig.in:type_name -> google.protobuf.Any
	29, // 17: atomos.AtomMessageConfig.out:type_name -> google.protobuf.Any
	2,  // 18: atomos.CosmosWatch.message_type:type_name -> atomos.CosmosWatchMessageType
	22, // 19: atomos.CosmosWatch.init_message:type_name -> atomos.CosmosRemoteConnectInit
	18, // 20: atomos.CosmosRemoteConnectInit.config:type_name -> atomos.CosmosLocalConfig
	3,  // 21: atomos.CosmosRemoteMessagingReq.from:type_name -> atomos.IDInfo
	3,  // 22: atomos.CosmosRemoteMessagingReq.to:type_name -> atomos.IDInfo
	29, // 23: atomos.CosmosRemoteMessagingReq.args:type_name -> google.protobuf.Any
	29, // 24: atomos.CosmosRemoteMessagingResp.reply:type_name -> google.protobuf.Any
	20, // 25: atomos.ElementConfig.MessagesEntry.value:type_name -> atomos.AtomMessageConfig
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_atomos_proto_init() }
func file_atomos_proto_init() {
	if File_atomos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_atomos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorCallerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteServerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelnetServerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelnetAdminConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CertConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosLocalConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AtomMessageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosWatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosRemoteConnectInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosRemoteGetAtomIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosRemoteGetAtomIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosRemoteMessagingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_atomos_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CosmosRemoteMessagingResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_atomos_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_atomos_proto_goTypes,
		DependencyIndexes: file_atomos_proto_depIdxs,
		EnumInfos:         file_atomos_proto_enumTypes,
		MessageInfos:      file_atomos_proto_msgTypes,
	}.Build()
	File_atomos_proto = out.File
	file_atomos_proto_rawDesc = nil
	file_atomos_proto_goTypes = nil
	file_atomos_proto_depIdxs = nil
}
