package go_atomos

const (
	OK = iota

	ErrFrameworkPanic

	ErrProcessRunnableInvalid

	ErrMainFnLoadCertFailed
	ErrMainFnCheckElementFailed
	ErrMainFnRunnableNotFound
	ErrMainFnIsReloading
	ErrMainFnElementNotFound
	ErrMainFnElementIsInvalid
	ErrMainFnReloadFailed
	ErrMainFnCannotKill
	ErrMainFnCannotSpawn
	ErrMainFnCannotMessage

	ErrCosmosConfigInvalid
	ErrCosmosConfigNodeNameInvalid
	ErrCosmosConfigLogPathInvalid
	ErrCosmosCertConfigInvalid
	ErrCosmosHasAlreadyRun
	ErrCosmosIsBusy
	ErrCosmosIsClosed

	ErrElementLoaded
	ErrElementReloadInvalid
	ErrElementMessageHandlerNotExists
	ErrElementMessageHandlerPanic
	ErrElementKillHandlerPanic

	ErrAtomosPanic
	ErrAtomosIsNotRunning
	ErrAtomosTaskInvalidFn
	ErrAtomosTaskNotExists

	ErrAtomMessageHandlerNotExists
	ErrAtomMessageHandlerPanic
	ErrAtomKillHandlerPanic
	ErrAtomKillElementNoImplement
	ErrAtomKillElementNotImplementAutoDataPersistence
	ErrAtomReloadInvalid
	ErrAtomFromIDInvalid
	ErrAtomToIDInvalid
	ErrAtomCallDeadLock
	ErrAtomNotExists
	ErrAtomExists
	ErrAtomPersistenceRuntime
	ErrAtomSpawnArgInvalid

	ErrElementCannotKill
)
