package go_atomos

const (
	OK = iota

	ErrFrameworkPanic

	ErrProcessRunnableInvalid

	ErrMainLoadCertFailed
	ErrMainCheckElementFailed
	ErrMainRunnableNotFound
	ErrMainIsReloading
	ErrMainElementNotFound
	ErrMainElementIsInvalid
	ErrMainReloadFailed
	ErrMainStartRunningPanic
	ErrMainCannotKill
	ErrMainCannotMessage
	ErrMainCannotScale

	ErrCosmosConfigInvalid
	ErrCosmosConfigNodeNameInvalid
	ErrCosmosConfigLogPathInvalid
	ErrCosmosCertConfigInvalid
	ErrCosmosHasAlreadyRun
	ErrCosmosIsBusy
	ErrCosmosIsClosed

	ErrElementLoaded
	ErrElementReloadInvalid
	ErrElementMessageHandlerNotExists
	ErrElementScaleHandlerNotExists
	ErrElementMessageHandlerPanic
	ErrElementKillHandlerPanic
	ErrElementSpawnArgInvalid
	ErrElementNotImplemented

	ErrAtomosPanic
	ErrAtomosIsStopping
	ErrAtomosIsNotRunning
	ErrAtomosTaskInvalidFn
	ErrAtomosTaskNotExists
	ErrAtomosNotSupportWormhole
	ErrAtomosPushTimeout

	ErrAtomMessageHandlerNotExists
	ErrAtomMessageHandlerPanic
	ErrAtomKillHandlerPanic
	ErrAtomKillElementNoImplement
	ErrAtomKillElementNotImplementAutoDataPersistence
	ErrAtomReloadInvalid
	ErrAtomFromIDInvalid
	ErrAtomToIDInvalid
	ErrAtomSpawnArgInvalid
	ErrAtomCallDeadLock
	ErrAtomNotExists
	ErrAtomExists
	ErrAtomPersistenceRuntime
	ErrAtomCannotScale

	ErrAtomNotImplemented
	ErrAtomMessageAtomType
	ErrAtomMessageArgType
	ErrAtomMessageReplyType

	ErrElementCannotKill
)
