// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: examples/go_atomos/for_test.proto

package atomos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 测试模式
type ForTestGreetingI_TestMode int32

const (
	// 无
	ForTestGreetingI_None ForTestGreetingI_TestMode = 0
	// 测试自我同步调用死锁
	ForTestGreetingI_SyncSelfCallDeadlock ForTestGreetingI_TestMode = 1
)

// Enum value maps for ForTestGreetingI_TestMode.
var (
	ForTestGreetingI_TestMode_name = map[int32]string{
		0: "None",
		1: "SyncSelfCallDeadlock",
	}
	ForTestGreetingI_TestMode_value = map[string]int32{
		"None":                 0,
		"SyncSelfCallDeadlock": 1,
	}
)

func (x ForTestGreetingI_TestMode) Enum() *ForTestGreetingI_TestMode {
	p := new(ForTestGreetingI_TestMode)
	*p = x
	return p
}

func (x ForTestGreetingI_TestMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForTestGreetingI_TestMode) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_go_atomos_for_test_proto_enumTypes[0].Descriptor()
}

func (ForTestGreetingI_TestMode) Type() protoreflect.EnumType {
	return &file_examples_go_atomos_for_test_proto_enumTypes[0]
}

func (x ForTestGreetingI_TestMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForTestGreetingI_TestMode.Descriptor instead.
func (ForTestGreetingI_TestMode) EnumDescriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{4, 0}
}

type ForTestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForTestData) Reset() {
	*x = ForTestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestData) ProtoMessage() {}

func (x *ForTestData) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestData.ProtoReflect.Descriptor instead.
func (*ForTestData) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{0}
}

type ForTestHelloI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ForTestHelloI) Reset() {
	*x = ForTestHelloI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestHelloI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestHelloI) ProtoMessage() {}

func (x *ForTestHelloI) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestHelloI.ProtoReflect.Descriptor instead.
func (*ForTestHelloI) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{1}
}

func (x *ForTestHelloI) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ForTestHelloO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ForTestHelloO) Reset() {
	*x = ForTestHelloO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestHelloO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestHelloO) ProtoMessage() {}

func (x *ForTestHelloO) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestHelloO.ProtoReflect.Descriptor instead.
func (*ForTestHelloO) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{2}
}

func (x *ForTestHelloO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ForTestSpawnArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ForTestSpawnArg) Reset() {
	*x = ForTestSpawnArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestSpawnArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestSpawnArg) ProtoMessage() {}

func (x *ForTestSpawnArg) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestSpawnArg.ProtoReflect.Descriptor instead.
func (*ForTestSpawnArg) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{3}
}

func (x *ForTestSpawnArg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ForTestGreetingI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode ForTestGreetingI_TestMode `protobuf:"varint,1,opt,name=mode,proto3,enum=go_atomos.ForTestGreetingI_TestMode" json:"mode,omitempty"`
}

func (x *ForTestGreetingI) Reset() {
	*x = ForTestGreetingI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestGreetingI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestGreetingI) ProtoMessage() {}

func (x *ForTestGreetingI) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestGreetingI.ProtoReflect.Descriptor instead.
func (*ForTestGreetingI) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{4}
}

func (x *ForTestGreetingI) GetMode() ForTestGreetingI_TestMode {
	if x != nil {
		return x.Mode
	}
	return ForTestGreetingI_None
}

type ForTestGreetingO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForTestGreetingO) Reset() {
	*x = ForTestGreetingO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_go_atomos_for_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForTestGreetingO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForTestGreetingO) ProtoMessage() {}

func (x *ForTestGreetingO) ProtoReflect() protoreflect.Message {
	mi := &file_examples_go_atomos_for_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForTestGreetingO.ProtoReflect.Descriptor instead.
func (*ForTestGreetingO) Descriptor() ([]byte, []int) {
	return file_examples_go_atomos_for_test_proto_rawDescGZIP(), []int{5}
}

var File_examples_go_atomos_for_test_proto protoreflect.FileDescriptor

var file_examples_go_atomos_for_test_proto_rawDesc = []byte{
	0x0a, 0x21, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x5f, 0x61, 0x74,
	0x6f, 0x6d, 0x6f, 0x73, 0x2f, 0x66, 0x6f, 0x72, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x1a, 0x0c,
	0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b,
	0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x23, 0x0a, 0x0d, 0x46,
	0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x49, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x29, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x4f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x46,
	0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x41, 0x72, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7c,
	0x0a, 0x10, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x49, 0x12, 0x38, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x24, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72,
	0x54, 0x65, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x2e, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x2e, 0x0a, 0x08,
	0x54, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x6c, 0x66, 0x43, 0x61,
	0x6c, 0x6c, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x01, 0x22, 0x12, 0x0a, 0x10,
	0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4f,
	0x32, 0x96, 0x02, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x41, 0x74, 0x6f, 0x6d,
	0x6f, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x70, 0x61,
	0x77, 0x6e, 0x12, 0x0b, 0x2e, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x4e, 0x69, 0x6c, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0f, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x18, 0x2e, 0x67,
	0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x49, 0x1a, 0x18, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d,
	0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x4f,
	0x22, 0x00, 0x12, 0x3d, 0x0a, 0x05, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x12, 0x1a, 0x2e, 0x67, 0x6f,
	0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x53,
	0x70, 0x61, 0x77, 0x6e, 0x41, 0x72, 0x67, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f,
	0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1b, 0x2e,
	0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73,
	0x74, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x5f,
	0x61, 0x74, 0x6f, 0x6d, 0x6f, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4f, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x5f, 0x61, 0x74, 0x6f, 0x6d, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_go_atomos_for_test_proto_rawDescOnce sync.Once
	file_examples_go_atomos_for_test_proto_rawDescData = file_examples_go_atomos_for_test_proto_rawDesc
)

func file_examples_go_atomos_for_test_proto_rawDescGZIP() []byte {
	file_examples_go_atomos_for_test_proto_rawDescOnce.Do(func() {
		file_examples_go_atomos_for_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_go_atomos_for_test_proto_rawDescData)
	})
	return file_examples_go_atomos_for_test_proto_rawDescData
}

var file_examples_go_atomos_for_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_go_atomos_for_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_examples_go_atomos_for_test_proto_goTypes = []interface{}{
	(ForTestGreetingI_TestMode)(0), // 0: go_atomos.ForTestGreetingI.TestMode
	(*ForTestData)(nil),            // 1: go_atomos.ForTestData
	(*ForTestHelloI)(nil),          // 2: go_atomos.ForTestHelloI
	(*ForTestHelloO)(nil),          // 3: go_atomos.ForTestHelloO
	(*ForTestSpawnArg)(nil),        // 4: go_atomos.ForTestSpawnArg
	(*ForTestGreetingI)(nil),       // 5: go_atomos.ForTestGreetingI
	(*ForTestGreetingO)(nil),       // 6: go_atomos.ForTestGreetingO
	(*Nil)(nil),                    // 7: atomos.Nil
}
var file_examples_go_atomos_for_test_proto_depIdxs = []int32{
	0, // 0: go_atomos.ForTestGreetingI.mode:type_name -> go_atomos.ForTestGreetingI.TestMode
	7, // 1: go_atomos.ForTestAtomos.ElementSpawn:input_type -> atomos.Nil
	2, // 2: go_atomos.ForTestAtomos.ElementSayHello:input_type -> go_atomos.ForTestHelloI
	4, // 3: go_atomos.ForTestAtomos.Spawn:input_type -> go_atomos.ForTestSpawnArg
	5, // 4: go_atomos.ForTestAtomos.Greeting:input_type -> go_atomos.ForTestGreetingI
	1, // 5: go_atomos.ForTestAtomos.ElementSpawn:output_type -> go_atomos.ForTestData
	3, // 6: go_atomos.ForTestAtomos.ElementSayHello:output_type -> go_atomos.ForTestHelloO
	1, // 7: go_atomos.ForTestAtomos.Spawn:output_type -> go_atomos.ForTestData
	6, // 8: go_atomos.ForTestAtomos.Greeting:output_type -> go_atomos.ForTestGreetingO
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_go_atomos_for_test_proto_init() }
func file_examples_go_atomos_for_test_proto_init() {
	if File_examples_go_atomos_for_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_go_atomos_for_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_go_atomos_for_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestHelloI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_go_atomos_for_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestHelloO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_go_atomos_for_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestSpawnArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_go_atomos_for_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestGreetingI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_examples_go_atomos_for_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForTestGreetingO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_go_atomos_for_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_go_atomos_for_test_proto_goTypes,
		DependencyIndexes: file_examples_go_atomos_for_test_proto_depIdxs,
		EnumInfos:         file_examples_go_atomos_for_test_proto_enumTypes,
		MessageInfos:      file_examples_go_atomos_for_test_proto_msgTypes,
	}.Build()
	File_examples_go_atomos_for_test_proto = out.File
	file_examples_go_atomos_for_test_proto_rawDesc = nil
	file_examples_go_atomos_for_test_proto_goTypes = nil
	file_examples_go_atomos_for_test_proto_depIdxs = nil
}
