// Code generated by protoc-gen-go-atomos. DO NOT EDIT.

package atomos

import (
	proto "google.golang.org/protobuf/proto"
)

const ForTestAtomosName = "ForTestAtomos"

////////////////////////////////////
/////////// 需要实现的接口 ///////////
////// Interface to implement //////
////////////////////////////////////

// ForTestAtomosElement is the atomos implements of ForTestAtomos element.

type ForTestAtomosElement interface {
	Atomos
	// Element的创建（自旋）方法
	// Element creation (spin) method
	// 与别不同的是，rpc的input参数表示Spawn时传入的参数，rpc的output参数表示Spawn时传入的数据（需要支持自动持久化）。
	Spawn(self ElementSelfID, data *ForTestData) *Error

	// 向Element发送SayHello消息
	// Send SayHello message to Element
	// I = Input
	// O = Output
	SayHello(from ID, in *ForTestHelloI) (out *ForTestHelloO, err *Error)
}

// ForTestAtomosAtom is the atomos implements of ForTestAtomos atom.

type ForTestAtomosAtom interface {
	Atomos

	// Spawn
	// Atom的创建（自旋）方法
	// Atom creation (spin) method
	// 与别不同的是，rpc的input参数表示Spawn时传入的参数，rpc的output参数表示Spawn时传入的数据（需要支持自动持久化）。
	Spawn(self AtomSelfID, arg *ForTestSpawnArg, data *ForTestData) *Error

	// 向Atom发送Greeting消息
	// Send Greeting message to Atom
	Greeting(from ID, in *ForTestGreetingI) (out *ForTestGreetingO, err *Error)
}

////////////////////////////////////
/////////////// 识别符 //////////////
//////////////// ID ////////////////
////////////////////////////////////

// Element: ForTestAtomos

type ForTestAtomosElementID struct {
	ID
	*IDTracker
}

// 获取某节点中的ElementID
// Get element id of node
func GetForTestAtomosElementID(c CosmosNode) (*ForTestAtomosElementID, *Error) {
	ca, err := c.CosmosGetElementID(ForTestAtomosName)
	if err != nil {
		return nil, err
	}
	return &ForTestAtomosElementID{ca, nil}, nil
}

// 向Element发送SayHello消息
// Send SayHello message to Element
// I = Input
// O = Output
// Sync
func (c *ForTestAtomosElementID) SayHello(callerID SelfID, in *ForTestHelloI, ext ...ArgsForBaseAtomos) (out *ForTestHelloO, err *Error) {
	/* CODE JUMPER 代码跳转 */ _ = func() { _ = forTestAtomosElementValue.SayHello }
	return forTestAtomosElementMessengerValue.SayHello().SyncElement(c, callerID, in, ext...)
}

// Async
func (c *ForTestAtomosElementID) AsyncSayHello(callerID SelfID, in *ForTestHelloI, callback func(out *ForTestHelloO, err *Error), ext ...ArgsForBaseAtomos) {
	/* CODE JUMPER 代码跳转 */ _ = func() { _ = forTestAtomosElementValue.SayHello }
	forTestAtomosElementMessengerValue.SayHello().AsyncElement(c, callerID, in, callback, ext...)
}

// Atom: ForTestAtomos

type ForTestAtomosAtomID struct {
	ID
	*IDTracker
}

// 创建（自旋）某节点中的一个Atom，并返回AtomID
// Create (spin) an atom in a node and return the AtomID
func SpawnForTestAtomosAtom(caller SelfID, c CosmosNode, name string, arg *ForTestSpawnArg) (*ForTestAtomosAtomID, *Error) {
	id, tracker, err := c.CosmosSpawnAtom(caller, ForTestAtomosName, name, arg)
	if id == nil {
		return nil, err.AddStack(nil)
	}
	return &ForTestAtomosAtomID{id, tracker}, err
}

// 获取某节点中的AtomID
// Get atom id of node
func GetForTestAtomosAtomID(c CosmosNode, name string) (*ForTestAtomosAtomID, *Error) {
	ca, tracker, err := c.CosmosGetAtomID(ForTestAtomosName, name)
	if err != nil {
		return nil, err
	}
	return &ForTestAtomosAtomID{ca, tracker}, nil
}

// Sync
func (c *ForTestAtomosAtomID) Greeting(callerID SelfID, in *ForTestGreetingI, ext ...ArgsForBaseAtomos) (out *ForTestGreetingO, err *Error) {
	/* CODE JUMPER 代码跳转 */ _ = func() { _ = forTestAtomosAtomValue.Greeting }
	return forTestAtomosAtomMessengerValue.Greeting().SyncAtom(c, callerID, in, ext...)
}

// Async
func (c *ForTestAtomosAtomID) AsyncGreeting(callerID SelfID, in *ForTestGreetingI, callback func(out *ForTestGreetingO, err *Error), ext ...ArgsForBaseAtomos) {
	/* CODE JUMPER 代码跳转 */ _ = func() { _ = forTestAtomosAtomValue.Greeting }
	forTestAtomosAtomMessengerValue.Greeting().AsyncAtom(c, callerID, in, callback, ext...)
}

// Atomos Interface

func GetForTestAtomosImplement(dev ElementDeveloper) *ElementImplementation {
	elem := NewImplementationFromDeveloper(dev)
	elem.Interface = GetForTestAtomosInterface(dev)
	elem.ElementHandlers = map[string]MessageHandler{
		"SayHello": func(from ID, to Atomos, in proto.Message) (proto.Message, *Error) {
			a, i, err := forTestAtomosElementMessengerValue.SayHello().ExecuteAtom(to, in)
			if err != nil {
				return nil, err.AddStack(nil)
			}
			return a.SayHello(from, i)
		},
	}
	elem.AtomHandlers = map[string]MessageHandler{
		"Greeting": func(from ID, to Atomos, in proto.Message) (proto.Message, *Error) {
			a, i, err := forTestAtomosAtomMessengerValue.Greeting().ExecuteAtom(to, in)
			if err != nil {
				return nil, err.AddStack(nil)
			}
			return a.Greeting(from, i)
		},
	}
	return elem
}
func GetForTestAtomosInterface(dev ElementDeveloper) *ElementInterface {
	elem := NewInterfaceFromDeveloper(ForTestAtomosName, dev)
	elem.ElementSpawner = func(s ElementSelfID, a Atomos, data proto.Message) *Error {
		dataT, _ := data.(*ForTestData)
		elem, ok := a.(ForTestAtomosElement)
		if !ok {
			return NewErrorf(ErrElementNotImplemented, "Element not implemented, type=(ForTestAtomosElement)")
		}
		return elem.Spawn(s, dataT)
	}
	elem.AtomSpawner = func(s AtomSelfID, a Atomos, arg, data proto.Message) *Error {
		argT, _ := arg.(*ForTestSpawnArg)
		dataT, _ := data.(*ForTestData)
		atom, ok := a.(ForTestAtomosAtom)
		if !ok {
			return NewErrorf(ErrAtomNotImplemented, "Atom not implemented, type=(ForTestAtomosAtom)")
		}
		return atom.Spawn(s, argT, dataT)
	}
	elem.ElementDecoders = map[string]*IOMessageDecoder{
		"SayHello": forTestAtomosElementMessengerValue.SayHello().Decoder(&ForTestHelloI{}, &ForTestHelloO{}),
	}
	elem.AtomDecoders = map[string]*IOMessageDecoder{
		"Greeting": forTestAtomosAtomMessengerValue.Greeting().Decoder(&ForTestGreetingI{}, &ForTestGreetingO{}),
	}
	return elem
}

// Atomos Internal

// Element Define

type forTestAtomosElementMessenger struct{}

func (m forTestAtomosElementMessenger) SayHello() Messenger[*ForTestAtomosElementID, *ForTestAtomosAtomID, ForTestAtomosElement, *ForTestHelloI, *ForTestHelloO] {
	return Messenger[*ForTestAtomosElementID, *ForTestAtomosAtomID, ForTestAtomosElement, *ForTestHelloI, *ForTestHelloO]{nil, nil, "SayHello"}
}

var forTestAtomosElementMessengerValue forTestAtomosElementMessenger
var forTestAtomosElementValue ForTestAtomosElement

// Atom Define

type forTestAtomosAtomMessenger struct{}

func (m forTestAtomosAtomMessenger) Greeting() Messenger[*ForTestAtomosElementID, *ForTestAtomosAtomID, ForTestAtomosAtom, *ForTestGreetingI, *ForTestGreetingO] {
	return Messenger[*ForTestAtomosElementID, *ForTestAtomosAtomID, ForTestAtomosAtom, *ForTestGreetingI, *ForTestGreetingO]{nil, nil, "Greeting"}
}

var forTestAtomosAtomMessengerValue forTestAtomosAtomMessenger
var forTestAtomosAtomValue ForTestAtomosAtom
