package main

import (
	"errors"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	atomosPackage   = protogen.GoImportPath("github.com/hwangtou/go-atomos")
	protobufPackage = protogen.GoImportPath("google.golang.org/protobuf/proto")
)

// generateFile generates a _grpc.pb.go file containing gRPC service definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_atomos.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-atomos. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g)
	return g
}

func serviceTitle(g *protogen.GeneratedFile, service *protogen.Service) {
	elementName := service.GoName
	head, tail := "////////// Element: ", " //////////"
	nameLen := len(elementName) + len(head) + len(tail)
	c := strings.Repeat("/", nameLen)
	g.P(c)
	g.P(head, elementName, tail)
	g.P(c)
	if len(service.Comments.Leading.String()) > 0 {
		g.P("//")
		g.P(service.Comments.Leading.String(), "//")
	}
	g.P()
}

// generateFileContent generates the atom definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Services) == 0 {
		return
	}

	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the atomos package it is being compiled against.")
	g.P()
	g.P("//////")
	g.P("//// INTERFACES")
	g.P("//")
	g.P()
	g.P()
	for _, service := range file.Services {
		elementName := service.GoName
		if elementName == "Main" {
			gen.Error(errors.New("cannot use element name \"Main\""))
			continue
		}
		serviceTitle(g, service)
		genIdInterface(g, service)
		genGetIdInterface(g, service)
		genAtomInterface(g, service)
	}
	g.P()
	g.P("//////")
	g.P("//// IMPLEMENTATIONS")
	g.P("//")
	g.P()
	for _, service := range file.Services {
		elementName := service.GoName
		if elementName == "Main" {
			gen.Error(errors.New("cannot use element name \"Main\""))
			continue
		}
		serviceTitle(g, service)
		genIdInternal(g, service)
		genImplement(file, g, service)
	}
}

func genIdInterface(g *protogen.GeneratedFile, service *protogen.Service) {
	elementName := service.GoName
	idName := service.GoName + "Id"

	g.P("const ", elementName, "Name = \"", elementName, "\"")
	g.P()
	g.P("// ", idName, " is the interface of ", elementName, " atomos.")
	g.P()

	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	g.Annotate(idName, service.Location)
	g.P("type ", idName, " interface {")
	if isWormhole(service) {
		g.P(atomosPackage.Ident("WormholeId"))
	} else {
		g.P(atomosPackage.Ident("Id"))
	}
	for _, method := range service.Methods {
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole" {
			continue
		}
		g.Annotate(idName+"."+method.GoName, method.Location)
		if method.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
			g.P(deprecationComment)
		}
		g.P()
		commentLen := len(method.Comments.Leading.String())
		if commentLen > 0 {
			g.P(method.Comments.Leading.String()[:commentLen-1])
		}
		methodSign(g, method)
		g.P()
	}
	g.P("}")
	g.P()
}

func genGetIdInterface(g *protogen.GeneratedFile, service *protogen.Service) {
	elementName := service.GoName
	idName := service.GoName + "Id"

	// NewClient factory.
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P(deprecationComment)
	}
	g.P("func Get", idName, " (c ", atomosPackage.Ident("CosmosNode"), ", name string) (", idName, ", error) {")
	g.P("ca, err := c.GetAtomId(", elementName, "Name, name)")
	g.P("if err != nil { return nil, err }")
	g.P("if c, ok := ca.(", idName, "); ok { return c, nil } else { return nil, ", atomosPackage.Ident("ErrAtomType"), " }")
	g.P("}")
	g.P()
}

func genIdInternal(g *protogen.GeneratedFile, service *protogen.Service) {
	idName := service.GoName + "Id"

	// Id structure.
	g.P("type ", noExport(idName), " struct {")
	if isWormhole(service) {
		g.P(atomosPackage.Ident("WormholeId"))
	} else {
		g.P(atomosPackage.Ident("Id"))
	}
	g.P("}")
	g.P()

	// Client method implementations.
	for _, method := range service.Methods {
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole"  {
			continue
		}
		g.P("func (c *", noExport(idName), ") ", method.GoName+"(from ", atomosPackage.Ident("Id"),
			", in *", g.QualifiedGoIdent(method.Input.GoIdent),
			") (*", g.QualifiedGoIdent(method.Output.GoIdent), ", error)", " {")
		g.P("r, err := c.Cosmos().MessageAtom(from, c, \"", method.GoName, "\", in)")
		g.P("if r == nil { return nil, err }")
		g.P("reply, ok := r.(*", method.Output.GoIdent, ")")
		g.P("if !ok { return nil, ", atomosPackage.Ident("ErrAtomMessageReplyType"), " }")
		g.P("return reply, nil")
		g.P("}")
		g.P()
	}
}

func genAtomInterface(g *protogen.GeneratedFile, service *protogen.Service) {
	elementName := service.GoName
	idName := service.GoName + "Id"

	spawnArgTypeName := "proto.Message"

	// Server struct.
	g.P("// ", elementName, " is the atomos implements of ", elementName, " atomos.")
	g.P()
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	g.Annotate(elementName, service.Location)
	g.P("type ", elementName, " interface {")
	if isWormhole(service) {
		g.P(atomosPackage.Ident("WormholeAtom"))
	} else {
		g.P(atomosPackage.Ident("Atom"))
	}
	for _, method := range service.Methods {
		g.Annotate(elementName+"."+method.GoName, method.Location)
		if method.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
			g.P(deprecationComment)
		}
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole"  {
			spawnSign(g, method)
			spawnArgTypeName = "*" + g.QualifiedGoIdent(method.Input.GoIdent)
		} else {
			methodSign(g, method)
		}
	}
	g.P("}")
	g.P()

	// Spawn
	g.P("func Spawn", elementName, "(c ", atomosPackage.Ident("CosmosNode"),
		", name string, arg ", spawnArgTypeName, ") (",
		idName, ", error) {")
	g.P("_, err := c.SpawnAtom(", elementName, "Name, name, arg)")
	g.P("if err != nil { return nil, err }")
	g.P("id, err := c.GetAtomId(", elementName, "Name, name)")
	g.P("if err != nil { return nil, err; }")
	g.P("if i, ok := id.(", idName, "); ok { return i, nil }")
	g.P("return nil, ", atomosPackage.Ident("ErrAtomType"))
	g.P("}")
}

func genImplement(file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service) {
	atomIdName := atomosPackage.Ident("Id")
	elementName := service.GoName
	idName := service.GoName + "Id"
	interfaceName := service.GoName + "Interface"

	g.P("func Get", elementName, "Interface(dev ", atomosPackage.Ident("ElementDeveloper"), ") *", atomosPackage.Ident("ElementInterface"), "{")
	g.P("elem := ", atomosPackage.Ident("NewInterfaceFromDeveloper("), elementName, "Name, dev)")
	if isWormhole(service) {
		g.P("elem.AtomIdConstructor = func(id ", atomIdName, ") ", atomIdName, " { return &", noExport(idName), "{id.(", atomosPackage.Ident("WormholeId"), ")} }")
	} else {
		g.P("elem.AtomIdConstructor = func(id ", atomIdName, ") ", atomIdName, " { return &", noExport(idName), "{id} }")
	}
	for _, method := range service.Methods {
		if method.GoName != "Spawn" && method.GoName != "SpawnWormhole"  {
			continue
		}
		g.P("elem.AtomSpawner = func(s ", atomosPackage.Ident("AtomSelf"), ", a ", atomosPackage.Ident("Atom"), ", arg, data ", protobufPackage.Ident("Message"), ") error {")
		g.P("argT, _ := arg.(*", method.Input.GoIdent, "); dataT, _ := data.(*", method.Output.GoIdent, ")")
		g.P("return a.(", elementName, ").Spawn(s, argT, dataT)")
		g.P("}")
	}
	g.P("elem.Config.Messages = map[string]*", atomosPackage.Ident("AtomMessageConfig"), "{")
	for _, method := range service.Methods {
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole"  {
			continue
		}
		g.P("\"", method.GoName, "\": ", atomosPackage.Ident("NewAtomCallConfig"), "(&", method.Input.GoIdent, "{}, &", method.Output.GoIdent, "{}),")
	}
	g.P("}")
	g.P("elem.AtomMessages = map[string]*", atomosPackage.Ident("ElementAtomMessage"), "{")
	for _, method := range service.Methods {
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole"  {
			continue
		}
		g.P("\"", method.GoName, "\": {")
		g.P("InDec: func(b []byte) (", protobufPackage.Ident("Message"), ", error) { return ", atomosPackage.Ident("MessageUnmarshal"), "(b, &", method.Input.GoIdent, "{}) },")
		g.P("OutDec: func(b []byte) (", protobufPackage.Ident("Message"), ", error) { return ", atomosPackage.Ident("MessageUnmarshal"), "(b, &", method.Output.GoIdent, "{}) },")
		g.P("},")
	}
	g.P("}")
	g.P("return elem")
	g.P("}")

	g.P()

	g.P("func Get", elementName, "Implement(dev ", atomosPackage.Ident("ElementDeveloper"), ") *", atomosPackage.Ident("ElementImplementation"), "{")
	g.P("elem := ", atomosPackage.Ident("NewImplementationFromDeveloper"), "(dev)")
	g.P("elem.Interface = Get", interfaceName, "(dev)")
	g.P("elem.AtomHandlers = map[string]", atomosPackage.Ident("MessageHandler"), "{")
	for _, method := range service.Methods {
		if method.GoName == "Spawn" || method.GoName == "SpawnWormhole"  {
			continue
		}
		g.P("\"", method.GoName, "\": func(from ", atomosPackage.Ident("Id"), ", to ", atomosPackage.Ident("Atom"), ", in ", protobufPackage.Ident("Message"), ") (", protobufPackage.Ident("Message"), ", error) {")
		g.P("req, ok := in.(*", method.Input.GoIdent, ")")
		g.P("if !ok { return nil, ", atomosPackage.Ident("ErrAtomMessageArgType"), "}")
		g.P("a, ok := to.(", elementName, ")")
		g.P("if !ok { return nil, ", atomosPackage.Ident("ErrAtomMessageAtomType"), "}")
		g.P("return a.", method.GoName, "(from, req)")
		g.P("},")
	}
	g.P("}")
	g.P("return elem")
	g.P("}")
}

const deprecationComment = "// Deprecated: Do not use."

func spawnSign(g *protogen.GeneratedFile, method *protogen.Method) {
	g.P("Spawn(self ", atomosPackage.Ident("AtomSelf"),
		", arg *", g.QualifiedGoIdent(method.Input.GoIdent),
		", data *", g.QualifiedGoIdent(method.Output.GoIdent),
		") error")
}

func methodSign(g *protogen.GeneratedFile, method *protogen.Method) {
	g.P(method.GoName+"(from ", atomosPackage.Ident("Id"),
		", in *", g.QualifiedGoIdent(method.Input.GoIdent),
		") (*", g.QualifiedGoIdent(method.Output.GoIdent), ", error)")
}
func isWormhole(service *protogen.Service) bool {
	for _, method := range service.Methods {
		if method.GoName == "SpawnWormhole" {
			return true
		}
	}
	return false
}

func noExport(s string) string {
	return strings.ToLower(s[:1]) + s[1:]
}
